/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import com.mycompany.proyectodetpv.PantPrincipal;
import com.mycompany.proyectodetpv.Producto;
import java.awt.Component;
import java.awt.Container;
import static java.awt.SystemColor.text;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import org.w3c.dom.NodeList;

/**
 * Componente visual que representa una categoría en la columna lateral.
 *
 * Cada instancia mantiene una lista de objetos {@link com.mycompany.proyectodetpv.Producto}
 * asociados y muestra el nombre de la categoría. Proporciona métodos para añadir y
 * eliminar productos, así como para obtener y modificar el nombre.
 *
 * Está pensado para usarse dentro de un `BoxLayout` vertical en la ventana
 * principal (`PantPrincipal`).
 *
 * @author mpvlm
 */
public class Categoria extends javax.swing.JPanel {

    public static NodeList getElementsByTagName(String producto) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String nombre;
    private List<Producto> productos = new ArrayList<>();

    /**
     * Añade un producto lógico a la lista de productos de esta categoría.
     *
     * @param producto objeto {@link com.mycompany.proyectodetpv.Producto} a añadir
     */
    public void agregarProducto(Producto producto) {
        productos.add(producto);
    }

    /**
     * Elimina el producto indicado de la lista de esta categoría.
     *
     * @param producto objeto {@link com.mycompany.proyectodetpv.Producto} a eliminar
     */
    public void eliminarProducto(Producto producto) {
        productos.remove(producto);
    }

    /**
     * Elimina los productos cuyo nombre coincida con el nombre indicado.
     *
     * @param nombreProducto nombre del producto a eliminar
     * @return {@code true} si se eliminó al menos un producto, {@code false} en caso contrario
     */
    public boolean eliminarProductoPorNombre(String nombreProducto) {
        return productos.removeIf(prod -> prod.getNombre().equals(nombreProducto));
    }

    /**
     * Devuelve la lista de productos asociados a esta categoría.
     *
     * @return lista (mutable) de {@link com.mycompany.proyectodetpv.Producto}
     */
    public List<Producto> getProductos() {
        return productos;
    }

    /**
     * Crea una nueva instancia de {@code Categoria} con el nombre indicado.
     *
     * @param text nombre inicial de la categoría
     */
    public Categoria(String text) {
        initComponents();
        setNombre(text);
        productos = new ArrayList<>();
        // Ensure the component aligns to the left when placed in a BoxLayout Y_AXIS
        setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        // Make inner panel stretch horizontally as well
        jPanel1.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
    }

    /**
     * Obtiene el nombre de la categoría.
     *
     * @return nombre de la categoría
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Establece el nombre visible e interno de la categoría.
     *
     * @param nombre nuevo nombre de la categoría
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
        jLabel1.setText((nombre == null || nombre.isEmpty()) ? "Categoría" : nombre);
        this.setName(this.nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        // Make the category occupy the full width of the parent (BoxLayout Y_AXIS)
        // and have a fixed height of 60 pixels.
        setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
        setMinimumSize(new java.awt.Dimension(100, 60));
        setPreferredSize(new java.awt.Dimension(100, 60));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categoria");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Container top = SwingUtilities.getAncestorOfClass(PantPrincipal.class, Categoria.this);
        if (top instanceof PantPrincipal owner) {
            // If double-click and deletion mode active, confirm and delete this category
            if (evt.getClickCount() == 2 && owner.isModoEliminacionActivo()) {
                int resp = javax.swing.JOptionPane.showConfirmDialog(owner,
                        "¿Eliminar la categoría '" + nombre + "' y sus productos?",
                        "Confirmar eliminación",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                if (resp == javax.swing.JOptionPane.YES_OPTION) {
                    owner.eliminarCategoriaPorNombre(nombre);
                }
                return;
            }
            for (Component c : owner.basePProducto.getComponents()) {
                c.setVisible(nombre.equals(c.getName()));
            }
            owner.basePProducto.revalidate();
            owner.basePProducto.repaint();
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
