/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectodetpv;

import componentes.Categoria;
import componentes.NuevoProducto;
import java.awt.Component;

/**
 *
 * @author mpvlm
 */
public class FormularioProducto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioProducto.class.getName());
    private PantPrincipal owner;
    private Object componentes;

    /**
     * Creates new form FormularioProducto
     */
    public FormularioProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.owner = (PantPrincipal) parent;
        initComponents();

    }
    private String rutaImagen;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtnCancelar = new javax.swing.JButton();
        aniadirProd = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 2, 0));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton2.setBackground(new java.awt.Color(255, 190, 185));
        jButton2.setText("Añadir  Imagen");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Introduce el nombre del producto:");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jTextField2.setText("jTextField2");
        jPanel3.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Introduce el precio:");
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jTextField3.setText("jTextField3");
        jPanel5.add(jTextField3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnCancelar, new java.awt.GridBagConstraints());

        aniadirProd.setText("Añadir");
        aniadirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aniadirProdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(aniadirProd, gridBagConstraints);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void aniadirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aniadirProdActionPerformed

        // Datos del formulario
        String nombre = jTextField2.getText().trim();
        String precio = jTextField3.getText().trim();
        if (nombre.isEmpty() || precio.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes introducir nombre y precio.");
            return;
        }
        float precioFloat;
        try {
            precioFloat = Float.parseFloat(precio);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.");
            return;
        }
        if (precioFloat < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio no puede ser negativo.");
            return;
        }

// Panel de productos activo (visible)
        Component panelActivo = null;
        for (Component comp : owner.basePProducto.getComponents()) {
            if (comp instanceof javax.swing.JPanel && comp.isVisible()) {
                panelActivo = comp;
                break;
            }
        }
        if (panelActivo == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna categoría activa.");
            return;
        }

//Crear y añadir el producto lógico
        Producto producto = new Producto(nombre, precioFloat, 1, rutaImagen);
        String categoriaNombre = null;
        for (Component comp : owner.panelCategoria.getComponents()) {
            if (comp instanceof Categoria cat && cat.getName().equals(panelActivo.getName())) {
                cat.agregarProducto(producto);
                 categoriaNombre = cat.getName();
                break;
            }
        }
        if (categoriaNombre == null || categoriaNombre.isEmpty()) {
            categoriaNombre = panelActivo.getName();
        }

// Añadir el visual
        NuevoProducto nuevoVisual = new NuevoProducto(owner, categoriaNombre, nombre, precioFloat, rutaImagen);
        ((javax.swing.JPanel) panelActivo).add(nuevoVisual);
        panelActivo.revalidate();
        panelActivo.repaint();

// Guardar XML
        owner.guardarCategoriasDesdeInterfaz();


        this.dispose();


    }//GEN-LAST:event_aniadirProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Abro un selector de archivos para que el usuario elija una imagen
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Selecciona una imagen");
        selector.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);

        // Filtro para que solo se puedan elegir imágenes
        javax.swing.filechooser.FileNameExtensionFilter filtro = new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (.jpg, .png, .jpeg)", "jpg", "png", "jpeg");
        selector.setFileFilter(filtro);

        // Muestro el diálogo y compruebo si el usuario ha seleccionado algo
        int resultado = selector.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            // Obtengo la ruta del archivo seleccionado
            java.io.File archivoSeleccionado = selector.getSelectedFile();
            rutaImagen = archivoSeleccionado.getAbsolutePath();

            // Por ahora solo mostramos la ruta en consola
            System.out.println("Ruta seleccionada: " + rutaImagen);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioProducto dialog = new FormularioProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadirProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnCancelar;
    // End of variables declaration//GEN-END:variables
}
